<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>CA1515;CA1050;CA1054;CA1849;CA2007;CA2234</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="MelbourneDev.Sync" Version="0.1.0" />
    <PackageReference Include="MelbourneDev.Sync.Postgres" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SyncMappings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
